# Site settings
title: 任天恒的Blog
header-img: img/home-bg.jpg
email: rth211@qq.com
description: "任天恒的Blog"
baseurl: ""
url: "http://rth211.github.io"
twitter_username:
github_username:  rth211
facebook_username:  rth211

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
